# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Zodium' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'IBAnimatable'
 pod 'Alamofire', '~> 4.2'
 pod 'SwiftyJSON'
 pod 'IQKeyboardManager'
 pod 'SDWebImage'
 pod 'NVActivityIndicatorView'
 pod 'DropDown'
 pod 'SideMenu'
 pod 'Cosmos'
 pod 'Socket.IO-Client-Swift', '~> 15.2.0'
 pod 'Stripe'
 pod 'RSSelectionMenu'
 pod 'Firebase/Core'
 pod 'Firebase/Messaging'
 pod 'Fabric'
 pod 'Crashlytics'
 pod 'GoogleAnalytics'
 pod 'Firebase/Auth'
 pod 'Firebase/Firestore'
 pod 'FirebaseFirestoreSwift'
 pod 'JitsiMeetSDK'
 pod 'ObjectMapper'
 pod 'IBAnimatable'
 pod 'Alamofire', '~> 4.2'
 pod 'SwiftyJSON'
 pod 'IQKeyboardManager'
 pod 'SDWebImage'
 pod 'NVActivityIndicatorView'
 pod 'DropDown'
 pod 'SideMenu'
 pod 'Cosmos'
 pod 'Socket.IO-Client-Swift', '~> 15.2.0'
 pod 'Stripe'
 pod 'RSSelectionMenu'
 pod 'Firebase/Core'
 pod 'Firebase/Messaging'
 pod 'Fabric'
 pod 'Crashlytics'
 pod 'GoogleAnalytics'
 pod 'Firebase/Auth'
 pod 'Firebase/Firestore'
 pod 'FirebaseFirestoreSwift'
 pod 'JitsiMeetSDK'
 pod 'ObjectMapper'
 pod 'Stripe', '~> 21.9'
 pod 'Lightbox'

  # Pods for Zodium

end
